### ISSUE TITLE
Add DNS on Cloudflare for https://github.com/celestiaorg/node-rpc-docs for node-rpc-docs.celestia.org

### ISSUE THREAD

**Issue by jcstein** [celestiaorg/node-rpc-docs#2]
we’ll be hosting node rpc docs from the [repo](https://github.com/celestiaorg/node-rpc-docs) linked in title, which will be hooked up to github pages cc @sysrex 

```[tasklist]
### Tasks
- [x] https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site?platform=mac
- [x] set up dns for [node-rpc-docs.celestia.org](http://node-rpc-docs.celestia.org/)
- [x] the information can be found in github pages settings https://github.com/celestiaorg/node-rpc-docs (and will be similar to other cloudflare dns setups for docs)
```
